import React, {useEffect, useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const base = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000';
async function api(path, options) { const r=await fetch(base+path,{headers:{'Content-Type':'application/json'},...options}); const body=await r.json(); if(!r.ok) throw new Error(body.detail?.message||body.error?.message||'Request failed'); return body; }
function Risk({tier}) { return <strong className={'risk '+(tier||'').toLowerCase()}>{tier||'UNAVAILABLE'}</strong> }
function App(){const [cases,setCases]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[operator,setOperator]=useState(''),[reason,setReason]=useState('');
 const refresh=async()=>{setLoading(true);setError('');try{setCases((await api('/cases')).cases)}catch(e){setError(e.message)}finally{setLoading(false)}}; useEffect(()=>{refresh()},[]);
 const open=async id=>{try{setSelected(await api('/case/'+id))}catch(e){setError(e.message)}};
 const act=async action=>{try{let a=await api('/case/'+selected.case_id+'/confirm',{method:'POST',body:JSON.stringify({operator_id:operator,action,reason:action==='OVERRIDE'?reason:undefined})});setSelected({...selected,operator_actions:[...selected.operator_actions,a],operator_confirmation_state:a.action});setReason('')}catch(e){setError(e.message)}};
 return <main><h1>Voice Cipher <small>Operator dashboard</small></h1><p className="notice">Decision support only. Human operator action is authoritative.</p><button onClick={refresh}>Refresh cases</button>{error&&<p className="error">{error}</p>}<section className="layout"><aside><h2>Cases</h2>{loading?<p>Loading…</p>:cases.length?cases.map(c=><button className="case" onClick={()=>open(c.case_id)} key={c.case_id}><b>{c.case_id}</b><Risk tier={c.risk_tier}/><span>{c.channel} · {c.svi_score??'—'}</span></button>):<p>No cases available.</p>}</aside><article>{!selected?<p>Select a case to inspect its redacted evidence and recommendations.</p>:<><h2>{selected.case_id} <Risk tier={selected.risk_tier}/></h2><p>{selected.channel} · {selected.operator_confirmation_state}</p><h3>Risk & explainability</h3><pre>{JSON.stringify(selected.svi_result,null,2)}</pre><h3>Redacted evidence</h3><pre>{JSON.stringify(selected.evidence_bundle,null,2)}</pre><h3>Recommendations</h3><pre>{JSON.stringify(selected.service_recommendation,null,2)}</pre><h3>Operator decision</h3><input placeholder="Operator ID" value={operator} onChange={e=>setOperator(e.target.value)}/><textarea placeholder="Override reason (required for override)" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={!operator} onClick={()=>act('CONFIRM')}>Confirm</button><button disabled={!operator||!reason.trim()} onClick={()=>act('OVERRIDE')}>Override</button><h3>Audit history</h3>{selected.operator_actions.map((a,i)=><pre key={i}>{JSON.stringify(a,null,2)}</pre>)}</>}</article></section></main>}; createRoot(document.getElementById('root')).render(<App/>);
